version: '3.8'

services:
  cl-doctor:
    container_name: cl-doctor
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: freelawproject/doctor:latest
    networks:
      - cl_net_overlay

  mock_cl_doctor:
    container_name: mock_cl_doctor
    image: freelawproject/doctor:latest
    networks:
      - cl_net_overlay
    depends_on:
      - cl-doctor

networks:
  cl_net_overlay:
    driver: bridge
    external: true

