version: '3.8'

services:
  doctor:
    container_name: doctor
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: freelawproject/doctor:latest

  mock_web_app:
    container_name: mock_web_app
    image: freelawproject/doctor:latest
    depends_on:
      - doctor
