version: '3.8'

services:
  doctor:
    container_name: doctor
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: freelawproject/doctor
    networks:
      - cl_net_overlay

  mock_courtlistener:
    container_name: mock_cl_doctor
    image: freelawproject/doctor
    networks:
      - cl_net_overlay
    depends_on:
      - doctor

networks:
  cl_net_overlay:
    driver: bridge
    external: true

